FROM simplyadrian/allsalt:{{ image_tag }}

ADD {{ formula_name }} /srv/salt/{{ formula_name }}

ADD tests /opt/tests
ADD tests/pillar/ /srv/pillar

WORKDIR /srv/salt

RUN sed -i "s/#master: salt/master: localhost/g" /etc/salt/minion

{%- if 'centos' not in image_tag %}
RUN apt-get update && \
    apt-get install -y python-pip
{% endif %}

RUN pip install pytest
